### ISSUE TITLE
Build failed with exit code 65

### ISSUE THREAD

**Issue by vishal91** [Carthage/Carthage#1538]
* `carthage version`: '0.17.2'
* `xcodebuild -version`: Xcode 7.3.1 
* Are you using `--no-build`? NO
* Are you using `--no-use-binaries`? NO
* Are you using `--use-submodules`? NO

**Cartfile**
```
github "SwiftBond/Bond" ~> 4.0
github "ReactiveX/RxSwift" ~> 2.0
github "SnapKit/SnapKit" ~> 0.15.0
github "facebook/facebook-ios-sdk"
```

**Carthage Output**
```
*** Fetching facebook-ios-sdk
*** Fetching SnapKit
*** Fetching RxSwift
*** Fetching Bond
*** Fetching Bolts-ObjC
*** Checking out Bolts-ObjC at "1.8.4"
*** Downloading facebook-ios-sdk.framework binary at "4.16.1"
*** Checking out facebook-ios-sdk at "sdk-version-4.16.1"
*** Checking out SnapKit at "0.15.0"
*** Checking out RxSwift at "2.6.0"
*** Checking out Bond at "v4.3.1"
*** xcodebuild output can be found in /var/folders/rn/bnn3wf9x6kv20_4mmp8pjzr40000gn/T/carthage-xcodebuild.nuVkzG.log
*** Building scheme "Bolts-iOS-Dynamic" in Bolts.xcodeproj
*** Building scheme "Bond" in Bond.xcodeproj
*** Building scheme "FBSDKCoreKit-Dynamic" in FacebookSDK.xcworkspace
** BUILD FAILED **


The following build commands failed:
	CompileC ~/Library/Developer/Xcode/DerivedData/FacebookSDK-agxoabfiyarmlpasbdrglgkemhqt/Build/Intermediates/FBSDKCoreKit.build/Release-iphoneos/FBSDKCoreKit-Dynamic.build/Objects-normal/armv7/FBSDKGraphRequestPiggybackManager.o FBSDKCoreKit/Internal/Network/FBSDKGraphRequestPiggybackManager.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
~/Carthage/Checkouts/facebook-ios-sdk/FBSDKCoreKit/FBSDKCoreKit/FBSDKApplicationDelegate.h:77:35: error: no type or protocol named 'UIApplicationOpenURLOptionsKey'
A shell task (/usr/bin/xcrun xcodebuild -workspace ~/Carthage/Checkouts/facebook-ios-sdk/FacebookSDK.xcworkspace -scheme FBSDKCoreKit-Dynamic -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileC ~/Library/Developer/Xcode/DerivedData/FacebookSDK-agxoabfiyarmlpasbdrglgkemhqt/Build/Intermediates/FBSDKCoreKit.build/Release-iphoneos/FBSDKCoreKit-Dynamic.build/Objects-normal/armv7/FBSDKGraphRequestPiggybackManager.o FBSDKCoreKit/Internal/Network/FBSDKGraphRequestPiggybackManager.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

```

**Comment by mdiep** [comment]
Please in the xcodebuild output. Your dependency failed to build. This is unrelated to Carthage.

```
~/Carthage/Checkouts/facebook-ios-sdk/FBSDKCoreKit/FBSDKCoreKit/FBSDKApplicationDelegate.h:77:35: error: no type or protocol named 'UIApplicationOpenURLOptionsKey'
```

**Comment by vishal91** [comment]
But same Cartfile is build on another machine.

**Comment by mdiep** [comment]
Are you using the same versions of Carthage and Xcode on both machines?

**Comment by vishal91** [comment]
Yeah

**Comment by mdiep** [comment]
Have you tried clearing your derived data?

**Comment by vishal91** [comment]
Yeah. Cache too.

**Comment by asm09fsu** [comment]
Seeing this issue as well. We have one machine that has Xcode 8 only, and is building correctly. The other machine has Xcode 7.3.1 and Xcode 8, and it will successfully build using 7.3.1 (after changing via `xcode-select`), however fails on Xcode 8.

**Comment by mdiep** [comment]
Can you post the xcodebuild log?

**Comment by vishal91** [comment]
xcodebuild version is Xcode 7.3.1 . I downloaded Xcode 8 then removed it.

**Comment by awgeorge** [comment]
Same issue here, after upgrading to Xcode 8 - xcodebuild now fails. Using carthage 0.18.1.

Looks like it's an issue with building projects that contain swift references: `“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.`

**Comment by rbissoli** [comment]
I had the same **FBSDKApplicationDelegate** error but using cocoapods. The error is related to the facebook sdk update. Now they are using another method.

According to the apple docs, they read:

https://developer.apple.com/library/content/releasenotes/General/iOS10APIDiffs/Objective-C/UIKit.html

Modified -[UIApplicationDelegate application:openURL:options:]
Declaration
From	
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options
To	
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options


So. I think in xCode 7.3.1 it won't compile anymore. I've changed the facebook sdk according to the old signature and now it runs ok on 7.3.1. But as soon as possible I will update the project to xcode 8 cause I think more error like this will appear.

Thank you guys.
