### ISSUE TITLE
Can't build project with nested dependency due to pre built framework

### ISSUE THREAD

**Issue by Sealos** [Carthage/Carthage#2173]
* `carthage version`: 0.24.0
* `xcodebuild -version`: Xcode 8.3.3, Build version 8E3004b
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`?  Yes
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? Yes

**Cartfile**
```
github "mapbox/mapbox-navigation-ios" ~> 0.8.0
github "raphaelmor/Polyline" == 4.1.1
```

**Carthage Output**
```
Please update to the latest Carthage version: 0.25.0. You currently are on 0.24.0
*** No cache found for aws-sdk-ios, building with all downstream dependencies
*** Valid cache found for Mapbox-iOS-SDK, skipping build
*** No cache found for mapbox-telemetry-ios, building with all downstream dependencies
*** No cache found for Polyline, building with all downstream dependencies
*** No cache found for Pulley, building with all downstream dependencies
*** No cache found for SDWebImage, building with all downstream dependencies
*** No cache found for Solar, building with all downstream dependencies
*** Building scheme "AWSPolly" in AWSiOSSDKv2.xcodeproj
*** Building scheme "AWSCore" in AWSiOSSDKv2.xcodeproj
*** Building scheme "MapboxMobileMetrics" in MapboxMobileEvents.xcodeproj
*** Building scheme "Polyline" in Polyline.xcodeproj
*** Building scheme "MapboxDirections iOS" in MapboxDirections.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/stefanodecolli/Documents/git/ios-new/Carthage/Checkouts/MapboxDirections.swift/MapboxDirections.xcodeproj -scheme MapboxDirections\ iOS -configuration Release -derivedDataPath /Users/stefanodecolli/Library/Caches/org.carthage.CarthageKit/DerivedData/MapboxDirections.swift/v0.10.5 -sdk iphonesimulator -destination platform=iOS\ Simulator,id=BB01F735-DAA3-4634-A90E-C067A45620ED -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/stefanodecolli/Documents/git/ios-new/Carthage/Checkouts/MapboxDirections.swift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/6f/_zqpkwjn2h195tcpg1d_5qxc0000gn/T/carthage-xcodebuild.I3DD56.log
```

The error in place is:
```
/Carthage/Checkouts/MapboxDirections.swift/MapboxDirections/MBRoute.swift:1:8: error: module compiled with Swift 4.0 cannot be imported in Swift 3.1: /Carthage/Checkouts/MapboxDirections.swift/Carthage/Build/iOS/Polyline.framework/Modules/Polyline.swiftmodule/i386.swiftmodule
```

Carthage is using a pre built framework on MapboxDirections iOS, even though the swift compiler doesn't match that version. As you may notice, I included polyline 4.1.1 which is swift 3.1, however, Mapbox Directions is using 4.1.1 built with swift 4

**Comment by Sealos** [comment]
The issue is caused by MapboxDirections Cartfile:
```
github "raphaelmor/Polyline" ~> 4.1.1
```

Which makes it use the version Polyline 4.2.0, and this in place downloads the framework built with the swift 4 compiler.

**Comment by ikesyo** [comment]
Looks like carthage didn't download any prebuilt frameworks (and actually Polyline doesn't have prebuilt ones: https://github.com/raphaelmor/Polyline/releases).

So this should be a case that you privously build your dependencies with Xcode 9 and the build caches are remaining on carthage's DerivedData directory. If you clear `~/Library/Caches/org.carthage.CarthageKit/DerivedData` dir or upgrade carthage to 0.25, the problem will be gone.

**Comment by ikesyo** [comment]
I've succeeded to build with Xcode 8.3.2.

```shell
$ carthage update --no-use-binaries --cache-builds --platform ios
*** Cloning Polyline
*** Cloning mapbox-navigation-ios
*** Cloning aws-sdk-ios
*** Cloning Solar
*** Cloning Pulley
*** Cloning mapbox-telemetry-ios
*** Cloning osrm-text-instructions.swift
*** Cloning MapboxDirections.swift
*** Downloading binary-only framework Mapbox-iOS-SDK at "https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json"
*** Cloning SDWebImage
*** Checking out Solar at "5ce2ca7baaa82b1abb0467642ae237faf674b645"
*** Checking out SDWebImage at "4.1.0"
*** Checking out Polyline at "v4.1.1"
*** Downloading Mapbox-iOS-SDK.framework binary at "3.6.3"
*** Checking out MapboxDirections.swift at "v0.10.5"
*** Checking out osrm-text-instructions.swift at "v0.3.4"
*** Checking out mapbox-navigation-ios at "v0.8.0"
*** Checking out mapbox-telemetry-ios at "v0.2.9"
*** Checking out Pulley at "1.4"
*** Checking out aws-sdk-ios at "2.6.0"
*** No cache found for aws-sdk-ios, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/ch/frqqndbn45l5dxldwqprh0jr0000gn/T/carthage-xcodebuild.3HgBkz.log
*** Valid cache found for Mapbox-iOS-SDK, skipping build
*** No cache found for mapbox-telemetry-ios, building with all downstream dependencies
*** No cache found for Polyline, building with all downstream dependencies
*** No cache found for Pulley, building with all downstream dependencies
*** No cache found for SDWebImage, building with all downstream dependencies
*** No cache found for Solar, building with all downstream dependencies
*** Building scheme "AWSPolly" in AWSiOSSDKv2.xcodeproj
*** Building scheme "AWSCore" in AWSiOSSDKv2.xcodeproj
*** Building scheme "MapboxMobileMetrics" in MapboxMobileEvents.xcodeproj
*** Building scheme "Polyline" in Polyline.xcodeproj
*** Building scheme "MapboxDirections iOS" in MapboxDirections.xcodeproj
*** Building scheme "OSRMTextInstructions iOS" in OSRMTextInstructions.xcodeproj
*** Building scheme "Pulley" in Pulley.xcodeproj
*** Building scheme "SDWebImage iOS" in SDWebImage.xcworkspace
*** Building scheme "Solar" in Solar.xcodeproj
*** Building scheme "MapboxCoreNavigation" in MapboxNavigation.xcodeproj
*** Building scheme "MapboxNavigation" in MapboxNavigation.xcodeproj
```

**Comment by Sealos** [comment]
I see! I cleared the derived data, but not the Carthage derived data, I will try again and report back.

Thanks a lot!
